# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af8cf863fafad01b8b1c9f9ea31b079a899a36b13bd500b0ddf55c620b5cf86c73b3b850d59aa3b67df7ada52bee42981d1b42941e0af15f70452b55d92678e8

test:
  secret_key_base: f604d19af3d493ffe935939c0ee6707bb62b29481827f4da1475ed31fb178027433bb8796a72e1025689c6b99b692722620863b9a1624b9813a478d3a68e71ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
